/**
 * Post type enum — must match backend PostType values.
 */
export enum PostType {
    COMPANY_RECRUITING_JOB = 'COMPANY_RECRUITING_JOB',
    COMPANY_RECRUITING_INTERNSHIP = 'COMPANY_RECRUITING_INTERNSHIP',
    COMPANY_SEEKING_THESIS_PARTNER = 'COMPANY_SEEKING_THESIS_PARTNER',
    STUDENT_SEEKING_THESIS = 'STUDENT_SEEKING_THESIS',
    STUDENT_SEEKING_JOB = 'STUDENT_SEEKING_JOB',
    STUDENT_SEEKING_INTERNSHIP = 'STUDENT_SEEKING_INTERNSHIP',
    LECTURER_SEEKING_THESIS_STUDENT = 'LECTURER_SEEKING_THESIS_STUDENT',
}

/**
 * Job/work type enum — must match backend JobType values.
 */
export enum JobType {
    FULL_TIME = 'FULL_TIME',
    PART_TIME = 'PART_TIME',
    CONTRACT = 'CONTRACT',
    INTERNSHIP = 'INTERNSHIP',
    REMOTE = 'REMOTE',
    HYBRID = 'HYBRID',
}
