import { API_CONFIG } from './api.config';

export const API_ENDPOINTS = {
    ANALYTICS: {
        TRACK_PAGE_VIEW: `${API_CONFIG.BASE_URL}/api/public/analytics/page-view`,
        HEARTBEAT: `${API_CONFIG.BASE_URL}/api/public/analytics/heartbeat`,
    },
    AUTH: {
        LOGIN: `${API_CONFIG.PREFIX}/auth/login`,
        GOOGLE_LOGIN: `${API_CONFIG.PREFIX}/auth/google`,
        REGISTER: `${API_CONFIG.PREFIX}/auth/register`,
        REFRESH: `${API_CONFIG.PREFIX}/auth/refresh-token`,
        LOGOUT: `${API_CONFIG.PREFIX}/auth/logout`,
        VERIFY_EMAIL: `${API_CONFIG.PREFIX}/auth/verify-email`,
        RESEND_VERIFY_EMAIL: `${API_CONFIG.PREFIX}/auth/verify-email/resend`,
    },
    RESEARCH: {
        LIST: `${API_CONFIG.PREFIX}/research-papers`,
        LIST_PAGED: `${API_CONFIG.PREFIX}/research-papers/paged`,
        MY_PAPERS: `${API_CONFIG.PREFIX}/research-papers/my`,
        STUDENT_AUTHOR_SEARCH: `${API_CONFIG.PREFIX}/research-papers/student-authors/search`,
        DETAIL: (id: string) => `${API_CONFIG.PREFIX}/research-papers/${id}`,
        TRACK_VIEW: (id: string) => `${API_CONFIG.PREFIX}/research-papers/${id}/views`,
        TRACK_DOWNLOAD: (id: string) => `${API_CONFIG.PREFIX}/research-papers/${id}/downloads`,
        BOOKMARKS_MY: `${API_CONFIG.PREFIX}/research-papers/bookmarks/me`,
        BOOKMARK: (id: string) => `${API_CONFIG.PREFIX}/research-papers/${id}/bookmarks`,
        CATEGORIES: `${API_CONFIG.PREFIX}/research-categories`,
        SPECIALIZATIONS: `${API_CONFIG.PREFIX}/specializations`,
    },
    RECRUITMENT: {
        LIST: `${API_CONFIG.PREFIX}/posts`,
        LIST_PAGED: `${API_CONFIG.PREFIX}/posts/paged`,
        CATEGORIES: `${API_CONFIG.PREFIX}/recruitment-categories`,
        DETAIL: (id: string) => `${API_CONFIG.PREFIX}/posts/${id}`,
        CREATE: `${API_CONFIG.PREFIX}/posts`,
        UPDATE: (id: string) => `${API_CONFIG.PREFIX}/posts/${id}`,
        MY_POSTS: `${API_CONFIG.PREFIX}/posts/me`,
        APPLY: (id: string) => `${API_CONFIG.PREFIX}/posts/${id}/apply`,
        APPLICATIONS_MY: `${API_CONFIG.PREFIX}/posts/applications/me`,
        APPLICATIONS_RECEIVED: `${API_CONFIG.PREFIX}/posts/applications/received`,
        APPLICATION_DETAIL: (id: string) => `${API_CONFIG.PREFIX}/posts/applications/${id}`,
        APPLICATION_STATUS: (id: string) => `${API_CONFIG.PREFIX}/posts/applications/${id}/status`,
    },
    CONTENT: {
        RESEARCH_HERO: `${API_CONFIG.PREFIX}/content/research-hero`,
    },
    NEWS: {
        LIST: `${API_CONFIG.PREFIX}/news`,
        DETAIL: (id: string) => `${API_CONFIG.PREFIX}/news/${id}`,
    },
    PROFILE: {
        ME: `${API_CONFIG.PREFIX}/profile/me`,
        DETAIL: (id: string) => `${API_CONFIG.PREFIX}/profile/${id}`,
        DASHBOARD: `${API_CONFIG.PREFIX}/profile/me/dashboard`,
        STUDENT: `${API_CONFIG.PREFIX}/profile/me/student`,
        COMPANY: `${API_CONFIG.PREFIX}/profile/me/company`,
        LECTURER: `${API_CONFIG.PREFIX}/profile/me/lecturer`,
    },
    STORAGE: {
        RESEARCH_PDF_UPLOAD: `${API_CONFIG.PREFIX}/storage/research-pdfs`,
        RESEARCH_HERO_IMAGE_UPLOAD: `${API_CONFIG.PREFIX}/admin/storage/research-hero-images`,
        PROFILE_CV_UPLOAD: `${API_CONFIG.PREFIX}/storage/profile-cvs`,
        AVATAR_UPLOAD: `${API_CONFIG.PREFIX}/storage/avatars`,
    },
    ADMIN: {
        USERS: `${API_CONFIG.PREFIX}/admin/users`,
        MODERATION: `${API_CONFIG.PREFIX}/admin/moderation`,
        MODERATION_POSTS: `${API_CONFIG.PREFIX}/admin/moderation/posts`,
        MODERATION_PAPERS: `${API_CONFIG.PREFIX}/admin/moderation/papers`,
        MODERATION_POST_DETAIL: (id: string) => `${API_CONFIG.PREFIX}/admin/moderation/posts/${id}`,
        MODERATION_PAPER_DETAIL: (id: string) => `${API_CONFIG.PREFIX}/admin/moderation/papers/${id}`,
        CONTENT_RESEARCH_HERO: `${API_CONFIG.PREFIX}/admin/content/research-hero`,
        RBAC_PERMISSIONS: `${API_CONFIG.PREFIX}/admin/rbac/permissions`,
        RBAC_ROLES: `${API_CONFIG.PREFIX}/admin/rbac/roles`,
        RBAC_USERS: `${API_CONFIG.PREFIX}/admin/rbac/users`,
        RBAC_USER_OVERRIDES: (id: string) => `${API_CONFIG.PREFIX}/admin/rbac/users/${id}/overrides`,
        RESEARCH_CATEGORIES: `${API_CONFIG.PREFIX}/admin/research-categories`,
        RESEARCH_CATEGORY_DETAIL: (id: string) => `${API_CONFIG.PREFIX}/admin/research-categories/${id}`,
        SPECIALIZATIONS: `${API_CONFIG.PREFIX}/admin/specializations`,
        SPECIALIZATION_DETAIL: (id: string) => `${API_CONFIG.PREFIX}/admin/specializations/${id}`,
        RECRUITMENT_CATEGORIES: `${API_CONFIG.PREFIX}/admin/recruitment-categories`,
        RECRUITMENT_CATEGORY_DETAIL: (id: string) => `${API_CONFIG.PREFIX}/admin/recruitment-categories/${id}`,
        NEWS: `${API_CONFIG.PREFIX}/admin/news`,
        NEWS_DETAIL: (id: string) => `${API_CONFIG.PREFIX}/admin/news/${id}`,
        NOTIFICATIONS_STREAM: `${API_CONFIG.PREFIX}/admin/notifications/stream`,
        ANALYTICS_OVERVIEW: `${API_CONFIG.PREFIX}/admin/analytics/overview`,
    },
} as const;
